eliteEvents/eliteEvents/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('website.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls)
]

eliteEvents/website/urls.py
from django.urls import path

from . import views

app_name = 'website'

urlpatterns = [
    path('', views.HtmlRendering.index, name='index'),
    path('signin/', views.HtmlRendering.signin, name='signin'),
    path('createEvent/', views.HtmlRendering.createEventPage, name='createEventPage'),
    path('allEvents/', views.HtmlRendering.allEvents, name='allEvents'),
    path('myEvents/', views.HtmlRendering.myEvents, name='myEvents'),
    path('event/edit/<int:event_id>/', views.HtmlRendering.editEvent, name='editEvent'),
    path('lfg/', views.HtmlRendering.lfgPage, name='lfgPage'),
    path('register/', views.UserViews.register, name='register'),
    path('login/', views.UserViews.loginUser, name='loginUser'),
    path('logout/', views.UserViews.logoutUser, name='logoutUser'),
    path('setUserTz/', views.UserViews.setUserTz, name='setUserTz'),
    path('event/update/<int:event_id>/', views.EventViews.updateEvent, name='updateEvent'),
    path('event/remove/', views.EventViews.removeEvent, name='removeEvent'),
    path('event/create/', views.EventViews.createEvent, name='createEvent'),
    path('event/search/', views.EventViews.searchEvents, name='searchEvents'),
    path('event/details/', views.EventViews.eventDetails, name='eventDetails'),
    path('event/join/', views.EventViews.eventJoin, name='eventJoin'),
    path('lfg/create/', views.LFGViews.createLfgPost, name='createLfgPost'),
    path('lfg/check/', views.LFGViews.checkForNew, name='checkForNew'),
    path('search/systems/', views.Utility.searchSystems, name='searchSystems'),
    path('sitemap.xml', views.Utility.sitemap, name='sitemap'),
    path('robots.txt', views.Utility.robots, name='robots')
]

eliteEvents/templates/html/allEvents.html
{% extends "html/base.html" %}
{% block content %}
{% load staticfiles %}
          <main role="main" class="inner cover">
            <h1 class="cover-heading">{{ coverHeading }}</h1>
            {% if events %}
                <div class="row event-search-results">
                    {% for event in events %}
                        <div class="event-preview" data-id="{{ event.id }}">
                            {% csrf_token %}
                            {% if event.event_type == 'combat' %}
                                <img class="event-type-img-sm" src="http://edassets.org/img/pilots-federation/combat/rank-9-combat.png" alt="Combat" data-type="combat"/>
                            {% elif event.event_type == 'exploration' %}
                                <img class="event-type-img-sm" src="http://edassets.org/img/pilots-federation/explorer/rank-9.png" alt="Combat" data-type="combat"/>
                            {% else %}
                                <img class="event-type-img-sm" src="http://edassets.org/img/pilots-federation/trading/rank-9-trading.png" alt="Combat" data-type="combat"/>
                            {% endif %}
                            <p>{{ event.name }}</p>
                            <p>{{ event.start_date }}</p>
                            <span><i class="fa fa-users" aria-hidden="true"></i></span><span  class="attendee-count">{{ event.attendees.all.count }}</span>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    {% if events.has_other_pages %}
                        <ul class="pagination">
                            {% if events.has_previous %}
                                <li><a href="?page={{ events.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for page_number in page_range %}
                                {% if events.number == page_number %}
                                    <li class="active"><span>{{ page_number }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if events.has_next %}
                                <li><a href="?page={{ events.next_page_number }}">&raquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>
            {% else %}
                <p>No events at this time sorry :(</p>
            {% endif %}
          </main>
{% endblock %}

eliteEvents/templates/html/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <title>Elite Dangerous Events</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Event creator/ LFG for Elite Dangerous">
    <meta name="author" content="Christian Cecilia">
    <meta name="keywords" content="elite dangerous, events, ED, elite, dangerous, looking for group, lfg">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- ED Events CSS -->
    <link href="{% static 'css/ed_events_style.css' %}" rel="stylesheet"/>
  </head>
  <body>
    <!-- csrf token for set timezone -->
    {% csrf_token %}
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

            <header class="masthead clearfix">
              <h3 class="masthead-brand">Elite Dangerous Events</h3>

              <nav class="nav nav-masthead">
                <a class="nav-link {% if page == 'index' %}active{% endif %}" href="{% url 'website:index' %}">Home</a>
                <a class="nav-link {% if page == 'allEvents' %}active{% endif %}" href="{% url 'website:allEvents' %}">All Events</a>
                <a class="nav-link {% if page == 'lfg' %}active{% endif %}" href="{% url 'website:lfgPage' %}" >LFG</a>
                {% if user.is_authenticated %}
                  <a class="nav-link {% if page == 'myEvents' %}active{% endif %}" href="{% url 'website:myEvents' %}" >My Events</a>
                  <a class="nav-link" href="/logout/">Log out</a>
                {% else %}
                  <a class="nav-link {% if page == 'signin' %}active{% endif %}" href="{% url 'website:signin' %}">Sign In/Register</a>
                {% endif %}
              </nav>
            </header>
            {% block content %}
            {% endblock %}
            <footer class="mastfoot">
            <div class="inner">
              <p>
                Created by CMDR<a class="footer-link" href="mailto:christian.cecilia1@gmail.com?Subject=Elite%20Dangerous%20Events"> Doughboy856</a><br> with <del>love</del> lasers
              </p>
              <p>
                <p>Servers Cost please</p>
                <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                  <input type="hidden" name="cmd" value="_s-xclick">
                  <input type="hidden" name="hosted_button_id" value="947LAS6JT3JX4">
                  <!-- <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"> -->
                  <input class="paypal-donate-img" type="image" src="{% static 'img/paypal-donate-btn.png' %}" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                  <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                </form>
              </p>
              <p>
                <a class="footer-link" href="https://github.com/CCecilia/eliteDangerousEvents" target="_blank">view source code</a>
              </p>
              <p class="footer-disclaimer">
                This website was created using assets and imagery from Elite Dangerous and <a class="footer-link" href="http://edassets.org/" target="_blank">Elite Dangerous Assests</a> for non-commercial purposes. It is not endorsed by nor reflects the views or opinions of Frontier Developments and no employee of Frontier Developments was involved in the making of it.
              </p>
            </div>
          </footer>

        </div>

      </div>

    </div>


    <!-- Popups -->
    <div id="event-details-popup">
      <img class="event-popup-type event-type-img-sm" src="" alt=""/>
      <p class="event-popup-name"></p>
      <p class="event-popup-description"></p>
      <p class="event-popup-location"></p>
      <p class="event-popup-start-date"></p>
      <p class="event-popup-start-time"></p>
      <p class="event-popup-end-date"></p>
      <p class="event-popup-end-time"></p>
      <span>
        <img class="event-popup-platform event-platform-img-icon" src="" alt=""/>
      </span>
      <span>
        <i class="fa fa-users" aria-hidden="true"></i>
      </span>
      <span class="attendance">
        
      </span>
      <input name="event-id" type="hidden">
      {% if user.is_authenticated %}
        {% if page == 'myEvents' %}
          <br>
          <br>
          <button class="edit-event event-option">Edit</button>
          <br>
          <br>
          <button class="remove-event event-option">Remove</button>
          <br>
          <br>
          <button class="share-event event-option">Share</button>

          <button class="reddit-share event-share-option">
            <a href="https://www.reddit.com/r/EliteDangerous/" target="_blank">
              <i class="fa fa-reddit-alien" aria-hidden="true"></i>
            </a>
          </button>
          <button class="share-cancel event-share-option">
            <i class="fa fa-times" aria-hidden="true"></i>
          </button>
        {% else %}
          <form name="join-event" method="POST" action="{% url 'website:eventJoin' %}">
            <input type="hidden" name="event-id">
            <br>
            <button class="join-event event-option" type="submit">Join</button>
          </form>
        {% endif %}
      {% else %}
        <br>
        <br>
        <button class="show-signin-required-popup event-option">Join</button>
      {% endif %}
    </div>

    <div id="confirm-removal-popup">
      <p class="remove-confirm-msg">
        Are you sure?
      </p>
      <button class="remove-event-yes">Yes</button>
      <button class="remove-event-no">No</button>
    </div>

    <div id="signin-required-popup">
      <p>
        Please <a href="{% url 'website:signin' %}">sign in/register</a> in order to join or create events.
      </p>
      <button class="hide-signin-required-popup event-option">Close</button>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <!-- ED Events JS -->
    <script type="text/javascript" src="{% static 'js/ed_events_scripts.js' %}"></script>
    {% if page == 'lfg' %}<script type="text/javascript" src="{% static 'js/lfg_autoupdate.js' %}"></script>{% endif %}
  </body>
</html>

eliteEvents/templates/html/lfgPage.html
{% extends "html/base.html" %}
{% block content %}
{% load staticfiles %}
	<main role="main" class="inner cover">
		<h1 class="cover-heading">{{ coverHeading }}</h1>
    	<form class="lfg-post-form" name="lfg-post-form" method="POST" action="{% url 'website:createLfgPost' %}">
    		<div class="row lfg-post-form-open-close-wrap">
    			<div class="col-sm-6 text-left create-lfg-toggle">Create Post</div> 
    			<div class="col-sm-6 text-right create-lfg-toggle"><i class="fa fa-chevron-down toggle-lfg-post"></i></div> 
    		</div>
    		<div class="lfg-form-wrap">
				<div class="row">
			    	<div class="col-sm-6">
			    		<h3>Group Type</h3>
			            <ul class="lfg-type-list">
			            	<li>
			            		<img class="lfg-type-img" src="{% static 'img/rank-9-combat.png' %}" alt="Combat" data-type="combat"/><br>
			            		Combat
			            	</li>
			            	<li>
			            		<img class="lfg-type-img" src="{% static 'img/rank-9-exploration.png' %}" alt="Exploration" data-type="exploration"/><br>
			            		Exploration
			            	</li>
			            	<li>
			            		<img class="lfg-type-img" src="{% static 'img/rank-9-trading.png' %}" alt="Trading" data-type="trading"/><br>
			            		Trading
			            	</li>
			            </ul>
			            <input type="hidden" name="lfg-type"/>
			    	</div>
			    	<div class="col-sm-6">
			    		<h3>Platform</h3>
			    		<ul class="platform-type-list">
			            	<li>
			            		<img class="platform-type-img" src="{% static 'img/xbox-icon-ed-org.png' %}" alt="XBox" data-type="XB"/><br>
			            		XBox 
			            	</li>
			            	<li>
			            		<img class="platform-type-img" src="{% static 'img/Playstation-icon.png' %}" alt="Playstation" data-type="PS"/><br>
			            		Playstation
			            	</li>
			            	<li>
			            		<img class="platform-type-img" src="{% static 'img/pc-icon.png' %}" alt="PC" data-type="PC"/><br>
			            		PC
			            	</li>
			            </ul>
			            <input type="hidden" name="platform-type"/>
			    	</div>
		    	</div>
		    	<hr>
		    	<div class="row">
		    		<div class="col-sm-6 col-md-4">
		    			<label class="lfg-label"for="commander-name">Commander Name</label>
		    			<input class="lfg-input" name="commander-name" placeholder="Commander Name"/>
		    		</div>
		    		<div class="col-sm-6 col-md-4">
		    			<label>Ship</label>
		    			<br>
		    			<select class="lfg-dropdown" name="ship">
		    				<option>Select your ship</option>
		    				<option value="Adder">Adder</option>
		    				<option value="Anaconda">Anaconda</option>
		    				<option value="Asp Explorer">Asp Explorer</option>
		    				<option value="Asp Scout">Asp Scout</option>
		    				<option value="Beluga Liner">Beluga Liner</option>
		    				<option value="Cobra MkIII">Cobra MkIII</option>
		    				<option value="Cobra MkIV">Cobra MkIV</option>
		    				<option value="Diamondback Explorer">Diamondback Explorer</option>
		    				<option value="Diamondback Scout">Diamondback Scout</option>
		    				<option value="Dolphin">Dolphin</option>
		    				<option value="Eagle MkII">Eagle MkII</option>
		    				<option value="Federal Assault Ship">Federal Assault Ship</option>
		    				<option value="Federal Corvette">Federal Corvette</option>
		    				<option value="Federal Dropship">Federal Dropship</option>
		    				<option value="Federal Gunship">Federal Gunship</option>
		    				<option value="Fer-de-Lance">Fer-de-Lance</option>
		    				<option value="Hauler">Hauler</option>
		    				<option value="Imperial Clipper">Imperial Clipper</option>
		    				<option value="Imperial Courier">Imperial Courier</option>
		    				<option value="Imperial Cutter">Imperial Cutter</option>
		    				<option value="Imperial Eagle">Imperial Eagle</option>
		    				<option value="Keelback">Keelback</option>
		    				<option value="Orca">Orca</option>
		    				<option value="Python">Python</option>
		    				<option value="Sidewinder">Sidewinder</option>
		    				<option value="Type-10 Defender">Type-10 Defender</option>
		    				<option value="Type-6 Transporter">Type-6 Transporter</option>
		    				<option value="Type-7 Transporter">Type-7 Transporter</option>
		    				<option value="Type-9 Heavy">Type-9 Heavy</option>
		    				<option value="Viper MkIII">Viper MkIII</option>
		    				<option value="Viper MkIV">Viper MkIV</option>
		    				<option value="Vulture">Vulture</option>
		    			</select>
		    		</div>
		    		<div class="col-sm-12 col-md-4">
		    			<label id="rank-label">Combat Rank</label>
		    			<br>
		    			<select class="lfg-dropdown" name="rank">
		    				<option value="harmless">Choose group type 1st</option>
		    			</select>
		    		</div>
		    	</div>
		    	<div class="row">
		    		<div class="col-sm-4">
		    			<label for="lfg-activity">Discord Server</label>
		    			<br>
		            	<input class="discord-input" name="lfg-discord-link" placeholder="Discord Server Link" type="text">
		    		</div>
		    		<div class="col-sm-4">
		    			<label for="lfg-activity">Location</label>
		    			<br>
			            <input class="event-location" name="lfg-location" placeholder="Location" type="text"  autocomplete="off">
			            <div class="location-results-wrapper">
			            	<table id="location-results-table"></table>
			            </div>
		    		</div>
		    		<div class="col-sm-4">
		    			<label for="lfg-message">Message</label>
		    			<br>
			            <textarea class="lfg-message" name="lfg-message" placeholder="Please add a brief message"></textarea>
		    		</div>
		    	</div>
		    	<div class="row">
		    		{% csrf_token %}
		    		<button class="btn create-lfg-post">Create</button>
		    	</div>
	    	</div>
	    </form>
		<div class="row lfg-posts">
			{% if posts %}
				<input type="hidden" name="lfg-last-post-id" value="{{ last_id }}"/>
				{% for post in posts %}
					<div class="row post-wrap">
						<div class="col-lg-2 lfg-post-type-col text-center">
							{% if post.post_type == 'combat' %}
			  					<img class="event-type-img-sm lfg-img" src="{% static 'img/rank-9-combat.png' %}" alt="Combat" data-type="combat"/>
			  				{% elif post.post_type == 'exploration' %}
			  					<img class="event-type-img-sm lfg-img" src="{% static 'img/rank-9-exploration.png' %}" alt="Exploration" data-type="exploration"/>
		  					{% else %}
		  						<img class="event-type-img-sm lfg-img" src="{% static 'img/rank-9-trading.png' %}" alt="Trading" data-type="trading"/>
	  						{% endif %}
	  						<br>
	  						{% if event.platform == 'XB' %}
			  					<img class="event-platform-img-icon lfg-img" src="{% static 'img/xbox-icon-ed-org.png' %}" alt="XBox" data-type="XB"/>
			  				{% elif event.platform == 'PS' %}
			  					<img class="event-platform-img-icon lfg-img" src="{% static 'img/Playstation-icon.png' %}" alt="Playstation" data-type="PS"/>
		  					{% else %}
		  						<img class="event-platform-img-icon lfg-img" src="{% static 'img/pc-icon.png' %}" alt="PC" data-type="PC" />
	  						{% endif %}
						</div>
						<div class="col-lg-4 lfg-post-commander-col text-left">
							<div class="row ">
								<div class="col-lg-5">
									<p>Commander: {{ post.commander }}</p>
									<p>Rank: {{ post.rank }}</p>
									<p>Ship: {{ post.ship }}</p>
								</div>
								<div class="col-lg-7 text-left">
									<p>Discord: {% if post.discord_link %}<a href="{{ post.discord_link }}" target="_blank">{{ post.discord_link|truncatechars:30 }}</a>{% else %}Not Given{% endif %}</p>
							    	<p>Location: {% if post.location %}{{ post.location }}{% else %}Not Given{% endif %}</p>
								</div>
							</div>
						</div>
						<div class="col-lg-4 lfg-post-msg-col">
							<p>{{ post.message }}</p>
						</div>
						<div class="col-lg-1 lfg-post-time-col">
							<p class="center-vert">{{ post.timeSinceCreation }}</p>
						</div>
					</div>
				{% endfor %}
			{% else %}
				<p class="center-hor">Sorry no posts at this time :(</p>
			{% endif %}
		</div>
		<div class="row">
            {% if posts.has_other_pages %}
                <ul class="pagination">
                    {% if posts.has_previous %}
                        <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for page_number in page_range %}
                        {% if posts.number == page_number %}
                            <li class="active"><span>{{ page_number }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </main>
{% endblock %}

eliteEvents/templates/html/myEvents.html
{% extends "html/base.html" %}
{% block content %}
{% load staticfiles %}
          <main role="main" class="inner cover">
            <h1 class="cover-heading">{{ coverHeading }}</h1>
            <div class="row">
                <div class="col-sm-12 col-lg-6 created-events">
                    <h2>Created Events <a href="{% url 'website:createEventPage' %}"><i class="fa fa-plus"></i></a></h2>
                    {% if created_events %}
                        <div class="row event-search-results">
                            {% for event in created_events %}
                                <div class="event-preview" data-id="{{ event.id }}">
                                    {% csrf_token %}
                                    {% if event.event_type == 'combat' %}
                                        <img class="event-type-img-sm" src="http://edassets.org/img/pilots-federation/combat/rank-9-combat.png" alt="Combat" data-type="combat"/>
                                    {% elif event.event_type == 'exploration' %}
                                        <img class="event-type-img-sm" src="http://edassets.org/img/pilots-federation/explorer/rank-9.png" alt="Combat" data-type="combat"/>
                                    {% else %}
                                        <img class="event-type-img-sm" src="http://edassets.org/img/pilots-federation/trading/rank-9-trading.png" alt="Combat" data-type="combat"/>
                                    {% endif %}
                                    <p>{{ event.name|truncatechars:18 }}</p>
                                    <p>{{ event.start_date.date }}</p>
                                    <span>
                                        {% if event.platform == 'PC' %}
                                            <img class="event-platform-img-icon" src="{% static 'img/pc-icon.png' %}" alt="PC" data-type="PC"/>
                                        {% elif event.platform == 'XB' %}
                                            <img class="event-platform-img-icon" src="{% static 'img/xbox-icon-ed-org.png' %}" alt="XBox" data-type="XB"/>
                                        {% else %}
                                            <img class="event-platform-img-icon" src="{% static 'img/Playstation-icon.png' %}" alt="Playstation" data-type="PS"/>
                                        {% endif %}
                                    </span>
                                    <span>
                                        <i class="fa fa-users" aria-hidden="true"></i>
                                    </span>
                                    <span  class="attendee-count">
                                        {{ event.attendees.all.count }}
                                    </span>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="row">
                            {% if created_events.has_other_pages %}
                                <ul class="pagination">
                                    {% if created_events.has_previous %}
                                        <li><a href="?created_page={{ created_events.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for page_number in created_events.paginator.page_range %}
                                        {% if created_events.number == page_number %}
                                            <li class="active"><span>{{ page_number }} <span class="sr-only">(current)</span></span></li>
                                        {% else %}
                                            <li><a href="?created_page={{ page_number }}">{{ page_number }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if created_events.has_next %}
                                        <li><a href="?created_page={{ created_events.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>
                            {% endif %}
                        </div>
                    {% else %}
                        <p class="text center">
                            No events created.
                        </p>
                    {% endif %}  
                </div>
                <div class="col-sm-12 col-lg-6 joined-events">
                    <h2>Joined Events</h2>
                    {% if joined_events %}
                        <div class="row event-search-results">
                            {% for event in joined_events %}
                                <div class="event-preview" data-id="{{ event.id }}">
                                    {% csrf_token %}
                                    {% if event.event_type == 'combat' %}
                                        <img class="event-type-img-sm" src="{% static 'img/rank-9-combat.png' %}" alt="Combat" data-type="combat"/>
                                    {% elif event.event_type == 'exploration' %}
                                        <img class="event-type-img-sm" src="{% static 'img/rank-9-exploration.png' %}" alt="Exploration" data-type="exploration"/>
                                    {% else %}
                                        <img class="event-type-img-sm" src="{% static 'img/rank-9-trading.png' %}" alt="Trading" data-type="trading"/>
                                    {% endif %}
                                    <p>{{ event.name|truncatechars:18 }}</p>
                                    <p>{{ event.start_date.date }}</p>
                                    <span>
                                        {% if event.platform == 'PC' %}
                                            <img class="event-platform-img-icon" src="{% static 'img/pc-icon.png' %}" alt="PC" data-type="PC"/>
                                        {% elif event.platform == 'XB' %}
                                            <img class="event-platform-img-icon" src="{% static 'img/xbox-icon-ed-org.png' %}" alt="XBox" data-type="XB"/>
                                        {% else %}
                                            <img class="event-platform-img-icon" src="{% static 'img/Playstation-icon.png' %}" alt="Playstation" data-type="PS"/>
                                        {% endif %}
                                    </span>
                                    <span>
                                        <i class="fa fa-users" aria-hidden="true"></i>
                                    </span>
                                    <span  class="attendee-count">
                                        {{ event.attendees.all.count }}
                                    </span>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="row">
                            {% if joined_events.has_other_pages %}
                                <ul class="pagination">
                                    {% if joined_events.has_previous %}
                                        <li><a href="?joined_page={{ joined_events.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for page_number in joined_events.paginator.page_range %}
                                        {% if joined_events.number == page_number %}
                                            <li class="active"><span>{{ page_number }} <span class="sr-only">(current)</span></span></li>
                                        {% else %}
                                            <li><a href="?joined_page={{ page_number }}">{{ page_number }}</a></li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if joined_events.has_next %}
                                        <li><a href="?joined_page={{ joined_events.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>
                            {% endif %}
                        </div>
                    {% else %}
                        <p class="text-center">
                            Find an event to <a href="{% url 'website:allEvents' %}">join</a>.
                        </p>
                    {% endif %}  
                </div>
            </div>
          </main>
{% endblock %}